apiVersion: v2
name: short-king
description: A Helm Chart for a Wordle Answer database
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: mongodb
  version: 15.4.3
  repository: https://charts.bitnami.com/bitnami