apiVersion: v1
kind: PersistentVolume
metadata:
  name: short-king-vol
  labels:
    app: shortking
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/short"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: short-king-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: shortking
  volumeMode: Filesystem