apiVersion: v1
kind: PersistentVolume
metadata:
  name: short-king-vol
  labels:
    app: shortking
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/short"