apiVersion: v1
kind: Service
metadata:
  labels:
    app: shortking-server
  name: shortking-service
spec:
  ports:
  - name: shortking-server
    port: 8000
    protocol: TCP
  selector:
    app: shortking-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: shortking-server
  name: shortking-server
spec:
  serviceName: "shortking-service"
  replicas: 1
  selector:
    matchLabels:
      app: shortking-server
  template:
    metadata:
      labels:
        app: shortking-server
    spec:
      containers:
        - image: criyl/shortking:latest
          name: shortking-server
          ports:
            - containerPort: 8000
          env:
          - name: MONGO_URI
            value: mongodb+srv://{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.password }}@{{ .Values.mongodb.host_url }}/?retryWrites=true
          - name: MONGO_DATABASE
            value: {{ .Values.mongodb.auth.database }}